#!/usr/bin/env python3
"""v12 manuscript consistency checker (inherits v11 mechanics).
The mechanical checks (labels/refs/cites/environments/delimiters) run on the
v12 instruments source and the unchanged v10 main article, plus the v12
correction-wave checks: the six R2-R7 repairs of the Wave-30 referee read
(R2 the corrected d_r-vanishing justification, R3 the (2,2)-slot clause,
R4 the b-pin in Step 4, R5 the two-step crux quotient, R6 the deck-convention
remark, R7 the lift-dependence marking of tau.Delta) and the removal of every
superseded v11 statement.  The v11 R1 checks and the v10 must-hold checks
re-run, with ONE documented phrasing update: the R5 repair replaces the
'finite-order element never lies in a subgroup generated by an
infinite-order element' sentence by the two-step version, so the old-phrase
check becomes the new-phrase check."""
import re
import sys
import subprocess
from collections import Counter

PATHS = {
    "INST": "/home/z/my-project/channel-supp-augmented/manuscript uploads v12/instruments-paper-revised12.txt",
    "MAIN": "/home/z/my-project/channel-supp-augmented/manuscript uploads v10/main-article-revised10.txt",
}
PDF = "/home/z/my-project/channel-supp-augmented/manuscript uploads v12/instruments-paper-revised12.pdf"
FAIL = []

CITE_RE = re.compile(r'\\cite(?:\[[^\]]*\])?\{([^}]+)\}')


def check(name, cond, msg):
    status = "PASS" if cond else "FAIL"
    if not cond:
        FAIL.append((name, msg))
    print(f"[{status}] {name}: {msg}")


texts = {}
for name, p in PATHS.items():
    with open(p, encoding='utf-8', errors='replace') as f:
        texts[name] = f.read()

for name, text in texts.items():
    lines = text.split('\n')
    print(f"\n{'='*70}\n{name} — mechanical checks\n{'='*70}")

    labels = set(re.findall(r'\\label\{([^}]+)\}', text))
    refs = set(re.findall(r'\\(?:ref|autoref|eqref)\{([^}]+)\}', text))
    dangling = sorted(refs - labels)
    check(name, not dangling, f"dangling refs: {dangling[:8] if dangling else 'none'}")
    dups = [l for l in labels if text.count(f'\\label{{{l}}}') > 1]
    check(name, not dups, f"duplicate labels: {dups[:8] if dups else 'none'}")

    cite_grps = CITE_RE.findall(text)
    cited_keys = set(k.strip() for c in cite_grps for k in c.split(','))
    bibitems = set(re.findall(r'\\bibitem\{([^}]+)\}', text))
    missbib = sorted(cited_keys - bibitems)
    check(name, not missbib, f"cite keys w/o bibitem: {missbib[:8] if missbib else 'none'}")

    envs = re.findall(r'\\begin\{(\w+)\}', text)
    ends = re.findall(r'\\end\{(\w+)\}', text)
    be, en = Counter(envs), Counter(ends)
    diff = {k: (be.get(k, 0), en.get(k, 0)) for k in set(be) | set(en)
            if be.get(k, 0) != en.get(k, 0)}
    check(name, not diff, f"begin/end mismatches: {diff if diff else 'none'}")

    ndb, nde = text.count('\\['), text.count('\\]')
    # KNOWN ARTIFACT (W26-diagnosed, byte-identical in v8-v12): the \[ / \]
    # counts include TikZ/matrix tokens; the deltas (INST 3, MAIN 4) are
    # pre-existing and unaffected by the v12 edits (verified: 211/208 in
    # v10, v11 AND v12).
    artifact_disp = (name == "INST" and (ndb, nde) == (211, 208)) or \
                    (name == "MAIN" and (ndb, nde) == (237, 233))
    if artifact_disp:
        print(f"[ARTIFACT] {name}: \\[ = {ndb}, \\] = {nde} "
              f"(pre-existing W26 checker artifact, v10/v11/v12-identical)")
    else:
        check(name, ndb == nde, f"\\[ = {ndb}, \\] = {nde}")

    t2 = text.replace('\\$', '')
    nd = len(re.findall(r'(?<!\\)\$', t2))
    # KNOWN ARTIFACT (W26-diagnosed): the MAIN TikZ $ count 3073 is odd in
    # every version v8-v12 (MAIN byte-unchanged since v10).
    artifact_dollar = (name == "MAIN" and nd == 3073)
    if artifact_dollar:
        print(f"[ARTIFACT] {name}: unescaped $ count = {nd} "
              f"(pre-existing W26 checker artifact, MAIN unchanged since v10)")
    else:
        check(name, nd % 2 == 0, f"unescaped $ count = {nd} (even?)")
        if name == "INST":
            v11path = ("/home/z/my-project/channel-supp-augmented/"
                       "manuscript uploads v11/instruments-paper-revised11.txt")
            v11 = open(v11path, encoding='utf-8', errors='replace').read()
            v11t2 = v11.replace('\\$', '')
            nd11 = len(re.findall(r'(?<!\\)\$', v11t2))
            print(f"      (INST dollar delta vs v11: +{nd - nd11} "
                  f"(v11 = {nd11}, v12 = {nd}); parity even: {nd % 2 == 0})")

    nonascii = set(ch for ln in lines for ch in ln if ord(ch) > 127)
    check(name, not nonascii, f"non-ASCII: {sorted(nonascii)[:10] if nonascii else 'none'}")

    nl, nr = text.count('\\left'), text.count('\\right')
    check(name, nl == nr, f"\\left = {nl}, \\right = {nr}")

I, M = texts["INST"], texts["MAIN"]
Inorm = I.replace("\n", " ")

print(f"\n{'='*70}\nV12 CORRECTION-WAVE CHECKS (the R2-R7 repairs)\n{'='*70}")
# --- the six repairs are PRESENT -------------------------------------------
check("V12", "for odd $r$ the target sits in odd\n$p$-degree, where "
      "$H^{\\mathrm{odd}}(BK;\\mathbb Z)=0$ by Step~3 below" in I or
      "for odd $r$ the target sits in odd $p$-degree, where "
      "$H^{\\mathrm{odd}}(BK;\\mathbb Z)=0$ by Step~3 below" in Inorm,
      "R2: the corrected odd-r step present")
check("V12", "even $r\\ge8$ the source fibre-degree is $8$ or $9$" in I,
      "R2: the even-r fibre-degree forcing present")
check("V12", "boundaries before the $E_8$-page" in I,
      "R2: the before-E8 boundary claim present")
check("V12", "In fibre degree nine,\n$d_2(\\beta z_1z_3z_5)=\\beta"
      "\\sigma_1z_3z_5$" in I or "In fibre degree nine, $d_2(\\beta z_1z_3z_5)"
      "=\\beta\\sigma_1z_3z_5$" in Inorm, "R2: the degree-nine killing present")
check("V12", "$d_4(\\tau z_1z_3z_5)=\n2\\tau^3z_1z_5\\ne0$" in I or
      "$d_4(\\tau z_1z_3z_5)= 2\\tau^3z_1z_5\\ne0$" in Inorm or
      "$d_4(\\tau z_1z_3z_5)=2\\tau^3z_1z_5\\ne0$" in Inorm,
      "R2: the torsion-coefficient killing present")
check("V12", "the $\\sigma_1$-multiple\ncoefficients are $d_2$-boundaries"
      in I or "the $\\sigma_1$-multiple coefficients are $d_2$-boundaries"
      in Inorm, "R2: the sigma1-multiple d2-boundary clause present")
check("V12", "is triangular in the monomials" in I,
      "R2: the triangular-divisibility clause present")
check("V12", "$E_2^{2,2}=0$ (the exterior algebra $\\Lambda(z_1,z_3,z_5)$ "
      "has no class of\ndegree two)" in I or
      "$E_2^{2,2}=0$ (the exterior algebra $\\Lambda(z_1,z_3,z_5)$ has no "
      "class of degree two)" in Inorm, "R3: the (2,2)-slot clause present")
check("V12", "$\\iota^*c_1=\\sigma_1+b\\,\\tau$" in I,
      "R4: the honest c1 display (sigma1 + b tau) present")
check("V12", "pins only the free components: the torsion restricts to zero"
      in I, "R4: the restriction-pins-only-free-components parenthetical "
      "present")
check("V12", "Hence $0=s^*(\\iota^*c_1)=s^*(\\sigma_1+b\\,\\tau)=bu$" in I,
      "R4: the b-pin equation present")
check("V12", "and $s^*\\tau=u$, $s$ being a section of the projection whose"
      " pullback\nclass $\\tau$ is" in I or
      "and $s^*\\tau=u$, $s$ being a section of the projection whose pullback"
      " class $\\tau$ is" in Inorm, "R4: the section justification present")
check("V12", "so $b=0$; and $2u^2=s^*(\\iota^*c_2)=\\varepsilon u^2$" in I,
      "R4: the extended pinning chain present")
check("V12", "Quotient out the direct summand\n$\\mathbb Z\\sigma_1^2$ "
      "first" in I or "Quotient out the direct summand $\\mathbb Z"
      "\\sigma_1^2$ first" in Inorm, "R5: the two-step quotient present")
check("V12", "a quotient by a direct summand leaves both\nthe class of "
      "$\\tau^2$ and the complementary summand unchanged" in I or
      "a quotient by a direct summand leaves both the class of $\\tau^2$ "
      "and the complementary summand unchanged" in Inorm,
      "R5: the direct-summand invariance clause present")
check("V12", "with the single incoming relation $\\sigma_2+2\\tau^2$, a "
      "class of infinite\norder" in I or
      "with the single incoming relation $\\sigma_2+2\\tau^2$, a class of "
      "infinite order" in Inorm, "R5: the single-relation clause present")
check("V12", "an element of order\nthree never lies in the subgroup "
      "generated by an infinite-order class" in I or
      "an element of order three never lies in the subgroup generated by "
      "an infinite-order class" in Inorm, "R5: the order-three argument "
      "(the single-generator setting) present")
check("V12", "the identification passes through the inversion\n"
      "$K\\backslash U(3)\\cong U(3)/K$" in I or
      "the identification passes through the inversion $K\\backslash U(3)"
      "\\cong U(3)/K$" in Inorm, "R6: the inversion remark present")
check("V12", "worst flip a sign, $x=\\pm\\gamma^*(\\tau)$; nothing below "
      "depends on the" in I, "R6: the sign-flip clause present")
check("V12", "the sign squaring away in $x^2=\\gamma^*(\\tau^2)$" in I,
      "R6: the invariance conclusion present")
check("V12", "these instances unconditional, the\n$\\sigma_i$ being the "
      "pinned pure classes of Step~4 below" in I or
      "these instances unconditional, the $\\sigma_i$ being the pinned pure "
      "classes of Step~4 below" in Inorm, "R7: the unconditional-sigma "
      "clause present")
check("V12", "is lift-dependent: the class of $\\Delta$ in\n"
      "$H^6(BK;\\mathbb Z)$ is fixed only up to a $\\tau^3$-tail" in I or
      "is lift-dependent: the class of $\\Delta$ in $H^6(BK;\\mathbb Z)$ is "
      "fixed only up to a $\\tau^3$-tail" in Inorm,
      "R7: the lift-dependence marking present")
check("V12", "$\\tau\\cdot(\\Delta+c\\,\\tau^3)=c\\,\\tau^4\\ne0$ when "
      "$c\\ne0$" in I, "R7: the tail-contribution formula present")
check("V12", "it is not used\nbelow" in I or "it is not used below" in Inorm,
      "R7: the unused-downstream note present")

# --- the superseded v11 statements are GONE ---------------------------------
check("V12", "by bidegree ($r$ even forces an odd" not in I,
      "OLD R2 justification 'by bidegree' gone")
check("V12", "where $H^{\\mathrm{odd}}(U(3))=0$" not in I,
      "OLD R2 premise 'H^odd(U(3)) = 0' gone")
check("V12", "the free generator is the unique class restricting" not in I,
      "OLD R4 uniqueness parenthetical gone")
check("V12", "both $\\sigma_1^2$ and $\\sigma_2+2\\tau^2$ generate\ninfinite "
      "cyclic subgroups" not in I and
      "both $\\sigma_1^2$ and $\\sigma_2+2\\tau^2$ generate infinite cyclic "
      "subgroups" not in Inorm, "OLD R5 per-subgroup phrasing gone")
check("V12", "finite-order element never lies in" not in I,
      "OLD R5 'finite-order element' phrasing gone")
check("V12", "alternating polynomial $\\Delta$ contains no monomial" not in I,
      "OLD R7 flat tau.Delta claim gone")
check("V12", I.count("\\tau\\Delta") == 1,
      "tau.Delta appears exactly once (the marked instance)")

print(f"\n{'='*70}\nV11 (R1) CHECKS THAT MUST STILL HOLD\n{'='*70}")
check("V11", "$H^6(B;\\mathbb Z)\\cong\\mathbb Z$, in which the discriminant "
      "class is twice a" in I, "the corrected statement clause (R1) present")
check("V11", "free part, integrally, is the invariant lattice" in I,
      "Step 2: the integral orbit-sum lattice statement (R1) present")
check("V11", "then $2$, $2$, $4$, $8$ in degrees $3$ to $6$" in I,
      "Step 2: the index values (R1) present")
check("V11", "H^6(BK;\\mathbb Z)\\ \\cong\\ \\mathbb Z\\{A_1,\\,S_1,\\,"
      "S_2,\\,\\sigma_3\\}" in I, "Step 3: the orbit-sum H^6(BK) display (R1) "
      "present")
check("V11", "$S_1-S_2=\\Delta$" in I, "Step 3: the orbit-sum relation (R1) "
      "present")
check("V11", "\\mathbb Z\\cdot\\langle S_1\\rangle" in I,
      "Step 7: H^6(B) = Z.<S1> (R1) present")
check("V11", "the discriminant\n$\\Delta=S_1-S_2=2S_1$ is twice a generator"
      in I or "the discriminant $\\Delta=S_1-S_2=2S_1$ is twice a generator"
      in Inorm, "Step 7: the twice-a-generator conclusion (R1) present")

print(f"\n{'='*70}\nV10 CHECKS THAT MUST STILL HOLD\n{'='*70}")
check("V10", "\\label{prop:cupsquare}" in I, "Proposition prop:cupsquare present")
check("V10", I.count("prop:cupsquare") >= 6, "prop:cupsquare referenced >= 6 times")
check("V10", "The cup square on the flag quotient: a hand derivation" in I,
      "the proposition title renders")
for step in ["Step 0 (the homogeneous-space model)", "Step 1 (the fibration",
             "Step 2 (the cohomology of $BK$", "Step 3 (the torsion product rule)",
             "Step 4 (the transgression values)", "Step 5 (the run",
             "Step 6 (the edge)", "Step 7 (the remaining degrees)"]:
    check("V10", step in I, f"proof step present: {step[:34]}")
check("V10", "d_4(z_3)=\\sigma_2+2\\tau^2" in I, "the pinned transgression value")
check("V10", "d_2(z_1)=\\sigma_1,\\qquad d_4(z_3)=\\sigma_2+2\\tau^2" in I,
      "the Step-4 display intact (b = 0 pinned)")
check("V10", "\\bibitem{HatcherSS}" in I, "HatcherSS bibitem present")
check("V10", "Flag-Quotient Width Obstructions" in I, "INST title intact")
check("V10", "flag manifolds; equivariant cohomology" in I, "INST keywords intact")
check("V10", "cite[Corollary~2]{NechitaEtAl2018}" in M, "MAIN Nechita cite intact")
check("V10", "(\\mathbb Z,\\ 0,\\ \\mathbb Z/3,\\ \\mathbb Z/3," in I,
      "the cohomology tuple stated in the proposition")
check("V10", "hand-derived, machine-certified, and independently re-implemented"
      in I, "the provenance phrase intact (INST)")
check("V10", "hand-derived, machine-certified, and independently re-implemented"
      in M, "the sync clause intact (MAIN)")
check("V10", "[closed in this version]" in I, "open problem (vi) still discharged")
ih, ig = I.find("\\bibitem{HatcherSS}"), I.find("\\bibitem{GuerraJana2025}")
check("V10", 0 < ih < ig, "HatcherSS bibitem in citation order before GuerraJana2025")
check("V10", I.count("S_1=\\chi_1^2\\chi_2+\\chi_2^2\\chi_3+\\chi_3^2\\chi_1")
      == 1, "S1 defined exactly once (Step 2)")
check("V10", "A_1=\\chi_1^3+\\chi_2^3+\\chi_3^3" in I, "A1 defined (Step 3)")
check("V10", "S_2=\\chi_1^2\\chi_3+\\chi_2^2\\chi_1+\\chi_3^2\\chi_2" in I,
      "S2 defined (Step 3)")

print(f"\n{'='*70}\nPDF RENDER VERIFICATION (pdftotext, whitespace-normalized)\n{'='*70}")
r = subprocess.run(["pdftotext", PDF, "-"], capture_output=True, text=True)
# normalize: whitespace; the ff/fi/fl/ffi ligatures; stray math-prime tokens
# that pdftotext lifts out of line order
pdfnorm = re.sub(r'\s+', ' ', r.stdout)
for lig, asc in [('ﬃ', 'ffi'), ('ﬄ', 'ffl'), ('ﬀ', 'ff'),
                 ('ﬁ', 'fi'), ('ﬂ', 'fl'), ('′', ''), ('′', '')]:
    pdfnorm = pdfnorm.replace(lig, asc)
pdfnorm = re.sub(r'\s+', ' ', pdfnorm)
pdf_phrases = [
    ("R2", "the target sits in odd"),
    ("R2", "boundaries before the"),
    ("R2", "kills every class whose coefficient survives multiplication by"),
    ("R2", "the torsion coefficients, which annihilate"),
    ("R2", "is triangular in the monomials"),
    ("R3", "has no class of"),
    ("R4", "pins only the free components"),
    ("R4", "being a section of the projection whose pullback"),
    ("R5", "Quotient out the direct summand"),
    ("R5", "a quotient by a direct summand leaves both"),
    ("R5", "with the single incoming relation"),
    ("R5", "never lies in the subgroup generated by an infinite-order"),
    ("R6", "the identification passes through the inversion"),
    ("R6", "nothing below depends on the choice, the sign squaring away"),
    ("R7", "these instances unconditional"),
    ("R7", "is lift-dependent"),
    ("R7", "it is not used"),
]
for tag, ph in pdf_phrases:
    check("PDF", ph in pdfnorm, f"{tag} phrase renders in the PDF: {ph[:48]!r}")
# the old statements must be absent from the rendered PDF:
for ph in ["by bidegree", "the unique class restricting",
           "generate infinite cyclic subgroups"]:
    check("PDF", ph not in pdfnorm, f"OLD statement absent from the PDF: {ph!r}")

print(f"\n{'='*70}\nRESULT: {len(FAIL)} failures" + ("" if not FAIL else f"\n{FAIL}"))
sys.exit(1 if FAIL else 0)
