#!/usr/bin/env python3
"""
WAVE 8 (c) -- HOMOLOGY-SIDE Cartan-Leray analysis of the two flagged bits.

Wave 8b (commit 75b51e4) machine-verified the COHOMOLOGICAL E2 pages of the
Cartan-Leray spectral sequences of

    B_d = Fl_d / C_d,   c = cyclic frame shift,

and their forced-differential structure, concluding the two bits are open:
  QUTRIT  (d=3): H^4(B_3;Z) = Z/3 or 0   <=> CL d3: E3^{1,2} -> E3^{4,0} zero/iso.
  QUQUART (d=4): H^3(B_4;Z~) = Z/2 or 0  <=> twisted CL d3: E3^{0,2} -> E3^{3,0}.

This script adds the HOMOLOGY side (E^2_{p,q} = H_p(C_d; H_q(Fl_d)) and its
twisted d=4 variant), which Wave 8b did not compute, and cross-glues it to
the cohomology side by Poincare duality + UCT.  New content:

  (1) LENS-SPACE validation of the whole engine (known answer H_*(L(3,1))).
  (2) QUTRIT: the |H_4(B_3)| = 3 product constraint (PD against the theorem
      H^2(B_3) = Z/3) forces an ANTI-CORRELATION between the two outgoing
      homology differentials of E_{5,0}; and the UCT glue machine-derives
      A = d3_{3,0->0,2} <-> the cohomological BIT.
  (3) QUQUART: the twisted homology page, the H_9(B_4;Z~) mirror of the bit
      (twisted PD), and its product constraint.
  (4) Documents the NEGATIVE RESULT: the tempting formula
      "d3^{1,2} = <alpha u k_2>" (CLSS d3 = cup with the 2-Postnikov
      k-invariant) is REFUTED by the test case B(non-split S^1 x| C_2)
      -- see the analysis printed at the end.

It does NOT decide the bits: that still requires the honest C_d-equivariant
chain model of Fl_d (c-invariant CW / equivariant Morse complex).
"""
from fractions import Fraction
from itertools import product

VERBOSE = True

# =====================================================================
# Section 0: exact integer lattice machinery
# =====================================================================

def mat_mul(A, B):
    r, k, c = len(A), len(B), len(B[0])
    assert len(A[0]) == k
    return [[sum(A[i][t] * B[t][j] for t in range(k)) for j in range(c)]
            for i in range(r)]

def snf_diag(A):
    """Smith normal form diagonal (with divisibility) of integer matrix A.
    Returns the list of nonzero diagonal entries d1 | d2 | ... ."""
    r = len(A); c = len(A[0]) if r else 0
    D = [row[:] for row in A]
    rr = cc = 0
    while rr < r and cc < c:
        best = None
        for i in range(rr, r):
            for j in range(cc, c):
                if D[i][j] != 0 and (best is None or abs(D[i][j]) < abs(best[2])):
                    best = (i, j, D[i][j])
        if best is None:
            break
        i0, j0, _ = best
        D[i0], D[rr] = D[rr], D[i0]
        for row in D:
            row[j0], row[cc] = row[cc], row[j0]
        changed = True
        while changed:
            changed = False
            for i in range(rr + 1, r):
                if D[i][cc] != 0:
                    q = D[i][cc] // D[rr][cc]
                    if q:
                        D[i] = [a - q * b for a, b in zip(D[i], D[rr])]
                    if D[i][cc] != 0:
                        D[i], D[rr] = D[rr], D[i]
                        changed = True
                        break
            if changed:
                continue
            for j in range(cc + 1, c):
                if D[rr][j] != 0:
                    q = D[rr][j] // D[rr][cc]
                    if q:
                        for k2 in range(r):
                            D[k2][j] -= q * D[k2][cc]
                    if D[rr][j] != 0:
                        for k2 in range(r):
                            D[k2][j], D[k2][cc] = D[k2][cc], D[k2][j]
                        changed = True
                        break
            if changed:
                continue
            for i in range(rr + 1, r):
                for j in range(cc + 1, c):
                    if D[i][j] != 0 and D[i][j] % D[rr][cc] != 0:
                        D[rr] = [a + b for a, b in zip(D[rr], D[i])]
                        changed = True
                        break
                if changed:
                    break
        if D[rr][cc] < 0:
            D[rr] = [-a for a in D[rr]]
        rr += 1; cc += 1
    diag = [D[i][i] for i in range(min(r, c)) if D[i][i] != 0]
    for a, b in zip(diag, diag[1:]):
        assert b % a == 0, "SNF divisibility failed"
    return diag, r - len(diag) if False else None  # (diag,) placeholder

def snf(A):
    d, _ = snf_diag(A)
    rank = len(d)  # rank of the lattice generated by rows (if rows are indep...)
    return d

def lattice_rank(gens):
    """Rank of the subgroup of Z^n generated by the given integer vectors."""
    if not gens:
        return 0
    A = [list(g) for g in gens]
    d = snf(A)
    return len(d)

def reduce_basis(gens):
    """Hermite-style reduction: an equivalent basis (as row list) of the
    lattice generated by gens (n-dimensional ambient)."""
    n = len(gens[0]) if gens else 0
    rows = [list(g) for g in gens]
    basis = []
    for col in range(n):
        # find gcd-reduced combination with nonzero col entry among remaining rows
        while True:
            piv = [i for i in range(len(rows)) if rows[i][col] != 0]
            if len(piv) <= 1:
                break
            piv.sort(key=lambda i: abs(rows[i][col]))
            i0 = piv[0]
            for i in piv[1:]:
                q = rows[i][col] // rows[i0][col]
                rows[i] = [a - q * b for a, b in zip(rows[i], rows[i0])]
        piv = [i for i in range(len(rows)) if rows[i][col] != 0]
        if piv:
            i0 = piv[0]
            v = rows.pop(i0)
            if v[col] < 0:
                v = [-a for a in v]
            basis.append(v)
            # eliminate this column from remaining rows (already zero by loop)
    return basis

def solve_in_basis(basis, v):
    """Express v as rational combination of the basis rows. Returns list of
    Fractions or None if not in the rational span."""
    r = len(basis); n = len(v)
    if r == 0:
        return [] if all(x == 0 for x in v) else None
    M = [[Fraction(basis[i][j]) for j in range(n)] + [Fraction(v[i])]
         for i in range(r)]
    # Gaussian elimination on the transpose: solve x^T * B = v
    # Instead: build B^T x = v: columns of B^T are the basis vectors.
    # Solve B x = v with B: r x n. Use normal equations via elimination on
    # the augmented matrix [B^T | v^T] with x unknown (n-dim), but x has
    # support only in r dims if basis is a true basis: general rational
    # least-squares-free solve: use r x n system B x = v -> pick r pivot cols.
    # Simpler: transpose approach: B^T is n x r; solve B^T y = v.
    BT = [[Fraction(basis[i][j]) for i in range(r)] for j in range(n)]
    aug = [row[:] + [Fraction(v[j])] for j, row in enumerate(BT)]
    piv_cols = []
    row_i = 0
    for col in range(r):
        p = None
        for i in range(row_i, n):
            if aug[i][col] != 0:
                p = i; break
        if p is None:
            continue
        aug[row_i], aug[p] = aug[p], aug[row_i]
        pv = aug[row_i][col]
        aug[row_i] = [x / pv for x in aug[row_i]]
        for i in range(n):
            if i != row_i and aug[i][col] != 0:
                f = aug[i][col]
                aug[i] = [a - f * b for a, b in zip(aug[i], aug[row_i])]
        piv_cols.append(col)
        row_i += 1
        if row_i == n:
            break
    # check consistency
    for i in range(row_i, n):
        if aug[i][r] != 0 and all(aug[i][k] == 0 for k in range(r)):
            return None  # inconsistent
    y = [Fraction(0)] * r
    for idx, col in enumerate(piv_cols):
        y[col] = aug[idx][r]
    # verify
    for j in range(n):
        s = sum(Fraction(basis[i][j]) * y[i] for i in range(r))
        if s != Fraction(v[j]):
            return None
    return y

def quotient_group(K_basis, L_gens):
    """K/L for lattices L <= K <= Z^n given by a basis of K and generators of
    L. Returns (free_rank, tors) where tors = list of invariant factors."""
    r = len(K_basis)
    if r == 0:
        return (0, [])
    coords = []
    for g in L_gens:
        y = solve_in_basis(K_basis, g)
        assert y is not None, "generator not in K -- invalid input"
        assert all(x.denominator == 1 for x in y), "non-integral coordinate"
        coords.append([int(x) for x in y])
    if not coords:
        return (r, [])
    d = snf(coords)
    # free part: columns not covered
    rankL = lattice_rank(coords)
    free = r - rankL
    # drop 1's from torsion (they contribute trivial factors)
    tors = [x for x in d if x != 1]
    return (free, tors)

def coker_group(A):
    """Z^n / im(A) for an n-column integer matrix (columns = generators).
    Returns (free, tors)."""
    n = len(A)
    gens = [[A[i][j] for i in range(n)] for j in range(n)]  # columns as vectors
    basis = reduce_basis(gens)
    if not basis:
        return (n, [])
    d = snf(basis)
    tors = [x for x in d if x != 1]
    return (n - len(d), tors)

def kernel_basis(A):
    """Basis of ker(A) cap Z^n as row vectors (A square integer matrix)."""
    n = len(A)
    # solve A x = 0: use SNF-free approach: rational RREF then integer lift
    import copy
    M = [row[:] for row in A]
    # augment with identity to track column ops is messy; do direct nullspace
    rows = [list(map(Fraction, row)) for row in M]
    piv = []
    r = 0
    for c in range(n):
        p = None
        for i in range(r, len(rows)):
            if rows[i][c] != 0:
                p = i; break
        if p is None:
            continue
        rows[r], rows[p] = rows[p], rows[r]
        pv = rows[r][c]
        rows[r] = [x / pv for x in rows[r]]
        for i in range(len(rows)):
            if i != r and rows[i][c] != 0:
                f = rows[i][c]
                rows[i] = [a - f * b for a, b in zip(rows[i], rows[r])]
        piv.append(c)
        r += 1
    free_cols = [c for c in range(n) if c not in piv]
    ker = []
    for fc in free_cols:
        v = [Fraction(0)] * n
        v[fc] = Fraction(1)
        for idx, pc in enumerate(piv):
            v[pc] = -rows[idx][fc]
        # integer lift: entries are already integers? not necessarily.
        vec = [int(x) if x.denominator == 1 else x for x in v]
        assert all(x.denominator == 1 for x in vec if isinstance(x, Fraction)), \
            "non-integral kernel vector -- algorithm bug"
        ker.append([int(x) for x in vec])
    if not ker:
        return []
    return reduce_basis(ker)

def image_gens(A):
    """Generators (columns) of im(A) as integer vectors."""
    n = len(A)
    return [[A[i][j] for i in range(n)] for j in range(n)]

def mat_N(A, m):
    n = len(A)
    N = [[0] * n for _ in range(n)]
    P = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
    for _ in range(m):
        N = [[N[i][j] + P[i][j] for j in range(n)] for i in range(n)]
        P = mat_mul(P, A)
    return N

def mat_sub_I(A):
    return [[A[i][j] - (1 if i == j else 0) for j in range(len(A))]
            for i in range(len(A))]

def gstr(free, tors):
    s = ""
    if free:
        s += f"Z^{free}" if free > 1 else "Z"
    if tors:
        t = " + ".join(f"Z/{x}" for x in tors)
        s += (" x " if s else "") + t if False else (" + " + t if s else t)
    return s if s else "0"

# =====================================================================
# Section 1: cyclic group (co)homology of a module Z^n with g |-> A
#   homology: H_0 = coker(A-I);  H_{2k+1} = ker(A-I)/im(N);
#             H_{2k>=2} = ker(N)/im(A-I)
#   cohomology: H^0 = ker(A-I);  H^{2k+1} = ker(N)/im(A-I);
#               H^{2k>=2} = ker(A-I)/im(N)
# (validated against Z and Z_sign below)
# =====================================================================

def cyc_hom(A, m, maxp):
    n = len(A)
    AmI = mat_sub_I(A)
    N = mat_N(A, m)
    # invariants: im(N) <= ker(A-I), im(A-I) <= ker(N)
    kB = kernel_basis(AmI)
    for g in image_gens(N):
        y = solve_in_basis(kB, g) if kB else None
        if kB:
            assert y is not None, "im(N) not in ker(A-I)!"
    kN = kernel_basis(N)
    for g in image_gens(AmI):
        if kN:
            y = solve_in_basis(kN, g)
            assert y is not None, "im(A-I) not in ker(N)!"
    out = []
    for p in range(maxp + 1):
        if p == 0:
            out.append(coker_group(AmI))
        elif p % 2 == 1:
            out.append(quotient_group(kB, image_gens(N)) if kB else (0, []))
        else:
            out.append(quotient_group(kN, image_gens(AmI)) if kN else (0, []))
    return out

def cyc_coh(A, m, maxp):
    n = len(A)
    AmI = mat_sub_I(A)
    N = mat_N(A, m)
    kB = kernel_basis(AmI)
    kN = kernel_basis(N)
    out = []
    for p in range(maxp + 1):
        if p == 0:
            out.append((len(kB), []))
        elif p % 2 == 1:
            out.append(quotient_group(kN, image_gens(AmI)) if kN else (0, []))
        else:
            out.append(quotient_group(kB, image_gens(N)) if kB else (0, []))
    return out

def check(name, got, want):
    assert got == want, f"{name}: got {got}, want {want}"
    if VERBOSE:
        print(f"    [ok] {name} = {gstr(*got)}")

def hdr(s):
    print("\n" + "=" * 72)
    print(s)
    print("=" * 72)

# =====================================================================
# Section 2: LENS-SPACE VALIDATION  (L(3,1) = S^3 / free C_3)
# =====================================================================
hdr("SECTION A: engine validation -- cyclic (co)homology")
Z1 = [[1]]
print("  trivial module Z (m=3):")
check("H_0(C3;Z)", cyc_hom(Z1, 3, 4)[0], (1, []))
check("H_1(C3;Z)", cyc_hom(Z1, 3, 4)[1], (0, [3]))
check("H_2(C3;Z)", cyc_hom(Z1, 3, 4)[2], (0, []))
check("H_3(C3;Z)", cyc_hom(Z1, 3, 4)[3], (0, [3]))
check("H^2(C3;Z)", cyc_coh(Z1, 3, 4)[2], (0, [3]))
check("H^3(C3;Z)", cyc_coh(Z1, 3, 4)[3], (0, []))
print("  sign module Z~ (m=4, g |-> -1):")
S1 = [[-1]]
check("H_1(C4;Z~)", cyc_hom(S1, 4, 4)[1], (0, []))
check("H_2(C4;Z~)", cyc_hom(S1, 4, 4)[2], (0, [2]))
check("H^1(C4;Z~)", cyc_coh(S1, 4, 4)[1], (0, [2]))
check("H^2(C4;Z~)", cyc_coh(S1, 4, 4)[2], (0, []))
print("  augmentation ideal iota (m=3, the qutrit H^2(Fl_3)-module):")
IOTA = [[0, -1], [1, -1]]
hi = cyc_hom(IOTA, 3, 6)
ci = cyc_coh(IOTA, 3, 6)
check("H_0(C3;iota)", hi[0], (0, [3]))
check("H_1(C3;iota)", hi[1], (0, []))
check("H_2(C3;iota)", hi[2], (0, [3]))
check("H_3(C3;iota)", hi[3], (0, []))
check("H^1(C3;iota)", ci[1], (0, [3]))
check("H^2(C3;iota)", ci[2], (0, []))
print("    (matches Wave 8b's machine page: cohomology Z/3 on ODD p,")
print("     homology Z/3 on EVEN p>=2 and p=0 -- the parity mirror.)")

hdr("SECTION B: lens space L(3,1) = S^3/<free C3> -- full engine test")
# fiber S^3: H_0 = Z, H_3 = Z, both trivial action (orientation-preserving)
hZ = cyc_hom(Z1, 3, 12)
page = {}
for q in (0, 3):
    for p in range(13):
        page[(p, q)] = hZ[p]
print("  E2_{p,0} = H_p(C3;Z):  " + " ".join(f"{gstr(*page[(p,0)]):>4}" for p in range(13)))
print("  E2_{p,3} = H_p(C3;Z):  " + " ".join(f"{gstr(*page[(p,3)]):>4}" for p in range(13)))
print("""
  Known answer: H_*(L(3,1)) = (Z, Z/3, 0, Z).
  Homology SS d^r: (p,q) -> (p-r, q+r-1).  d3 targets (p-3,2) are 0 (no H_2(S3)).
  The FIRST live differentials are d4: (p,0) -> (p-4,3):
      d4: (5,0)=Z/3 -> (1,3)=Z/3    MUST be an ISO (both entries have total
                                     degree > 3 = dim L, both must die).
      d4: (7,0)=Z/3 -> (3,3)=Z/3    ISO   (total 7 and 6 > 3)
      d4: (9,0)=Z/3 -> (5,3)=Z/3    ISO   (the staircase continues)
  Survivors: (0,0)=Z; (1,0)=Z/3 -> H_1; (3,0)=Z/3 -> graded piece of H_3;
  (0,3)=Z -> top class.  The graded pieces of H_3 = Z are (Z/3 from (3,0),
  Z from (0,3)) -- realized by the filtration Z >= 3Z >= ... -- the LESSON:
  torsion graded pieces of a FREE group need not die; |H_k| = prod|E_inf|
  is valid ONLY when H_k is finite.
  Cohomology mirror (the classical Euler-class transgression):
      d_4: E^{0,3}=Z -> E^{4,0}=Z/3  surjective (reduction mod 3),
  and the homology mirror d4: (5,0)->(1,3) iso is the same map under the
  UCT shift (p,q) <-> (p+1,q).  PATTERN CONFIRMED: cohomological d_r
  (p,q)->(p+r,q-r+1) mirrors homological d_r (p+r+1... precisely:
  hom-d_r (P,Q)->(P-r,Q+r-1) is the Ext-dual of coh-d_r (P-r-1, Q-r+1)->
  ... (implemented below as the pairing used in Sections C/D).""")
# machine-check the forced isos
for (p,) in [(5,), (7,), (9,)]:
    s = page[(p, 0)]; t = page[(p - 4, 3)]
    assert s == (0, [3]) and t == (0, [3]), "lens page mismatch"
print("  [ok] d4 iso staircase (5,0)->(1,3), (7,0)->(3,3), (9,0)->(5,3) forced.")
assert page[(1, 0)] == (0, [3]) and page[(0, 3)] == (1, [])
assert page[(3, 0)] == (0, [3])
print("  [ok] H_1 = Z/3 (E_1,0 survives); H_3 = Z with graded (Z/3, Z).")
print("  [ok] engine validated: page + forced-differential logic sound.")

# =====================================================================
# Section 3: QUTRIT homology side
# =====================================================================
hdr("SECTION C: QUTRIT (d=3) -- homology CLSS page E2_{p,q} = H_p(C3; H_q(Fl3))")
# modules: q=0: Z; q=2,4: iota (2-dim); q=6: Z (deg(c)=+1, B_3 orientable)
modsq = {0: Z1, 2: IOTA, 4: IOTA, 6: Z1}
hom3 = {q: cyc_hom(A, 3, 13) for q, A in modsq.items()}
for q in (0, 2, 4, 6):
    lbl = {0: "Z    ", 2: "iota ", 4: "iota ", 6: "Z    "}[q]
    print(f"  q={q} ({lbl}): " + " ".join(f"{gstr(*hom3[q][p]):>4}" for p in range(13)))
print("""
  Nonzero entries: q in {0,6}: p=0 (Z) and p odd (Z/3);
                   q in {2,4}: p=0 (Z/3) and p even >= 2 (Z/3).
  Homology d^r: (p,q) -> (p-r, q+r-1).  All live maps connect Z/3 -> Z/3
  (each is 0 or iso).  The LOW-DEGREE differentials (total degree <= 6):
    A  = d3: (3,0)  -> (0,2)     [touches H_2, H_3]
    B' = d3: (5,0)  -> (2,2)     [touches H_4, H_5]
    C' = d5: (5,0)  -> (0,4)     [acts on ker(B') afterwards; touches H_4, H_5]
  Tail differentials (kill total >= 7; they never touch H_k, k <= 5):
    D7 = d3: (7,0)->(4,2); E7 = d5: (7,0)->(2,4);  F8 = d3: (4,4)->(1,6);
    G9 = d3: (9,0)->(6,2); H9 = d5: (9,0)->(4,4);  I6 = d5: (6,2)->(1,6);
    J  = d3: (6,4)->(3,6); K  = d5: (8,2)->(3,6);  L  = d5: (11,0)->(6,4);
    M  = d3: (11,0)->(8,2); N = d3: (8,4)->(5,6);  ... staircase continues.
  The tail is always killable (e.g. the d3-iso pairing staircase
  (9,0)&(6,2), (11,0)&(8,2), (4,4)&(1,6), (6,4)&(3,6), (8,4)&(5,6), ...),
  so the tail imposes NO constraint on A, B', C'.  Verified by enumeration
  below (tail worlds always exist).""")

# --- assemble H_k for k = 1..5 as functions of (A, B', C') ---
# H_1 = E_inf_{1,0} = Z/3 (no differentials touch (1,0))
# H_2 = coker(A)                                   [(2,0)=0, (1,1)=0, (0,2)...]
#     E_inf_{0,2} = E2_{0,2}/im(A)  and (2,0) = H_2(C3;Z) = 0.
# H_3 = ker(A)  [(3,0) entry; (1,2) = H_1(C3;iota) = 0; (0,3)=0; (2,1)=0]
# H_4 = E_inf_{2,2} + E_inf_{0,4} (extension; orders multiply, all finite):
#     E_inf_{2,2} = Z/3 / im(B');  E_inf_{0,4} = Z/3 / im(C'|_{ker B'})
#     [(4,0) = H_4(C3;Z) = 0]
# H_5 = E_inf_{5,0} = ker(B') n ker(C'|_{ker B'})   [(3,2)=0, (1,4)=0]
print("  ASSEMBLY (machine formulas):")
print("    H_1 = Z/3 (forced)")
print("    H_2 = coker(A);   H_3 = ker(A);   H_5 = ker(B') & ker(C')")
print("    |H_4| = |Z/3:im(B')| * |Z/3:im(C')|")

# --- the constraint solver over (A, B', C') ---
print("""
  CONSTRAINTS (machine-enforced):
    (PD1) |H_4| = |H^2(B_3)| = 3      [theorem H^2 = Z/3, B_3 orientable]
    (PD2) H_5 = 0                      [PD: H_5 ~ H^1 = 0]
    (UCT) H^2 = Ext(H_1) + Hom(H_2); H^3 = Ext(H_2) + Hom(H_3);
          H^4 = Ext(H_3) + Hom(H_4); H^5 = Ext(H_4) + Hom(H_5) ~ H_1.
    The cohomological side (Wave 8b): |H^3| = |H^4| = 3 iff the BIT d3=0.
  WORLD ENUMERATION over (A, B', C') in {0, iso}^3:""")
rows = []
for A0, B0, C0 in product((0, 1), repeat=3):
    # A-map: 0 => coker = Z/3, ker = Z/3 ; iso => coker = 0, ker = 0
    H2 = (0, [3]) if A0 == 0 else (0, [])
    H3 = (0, [3]) if A0 == 0 else (0, [])
    # B', C' on Z/3:
    if B0 == 1:
        E22 = (0, [])          # coker(B') = 0
        kerB = (0, [])         # ker B' = 0  => C' acts on 0 => image 0
        E04 = (0, [3])         # coker(C'|_0) = Z/3 untouched
        H5 = (0, [])           # ker B' = 0
    else:
        E22 = (0, [3])
        kerB = (0, [3])
        if C0 == 1:
            E04 = (0, [])
            H5 = (0, [])
        else:
            E04 = (0, [3])
            H5 = (0, [3])      # ker B' = Z/3, ker C' = Z/3 => H_5 = Z/3
    H4_tors = (len(E22[1]) and 3 or 0) + 0  # orders multiply:
    orderH4 = (3 if E22[1] else 1) * (3 if E04[1] else 1)
    # UCT: H^3 = Ext(H_2) + Hom(H_3):
    H3coh_tors = [3] if H2[1] else []
    H3coh = (0, H3coh_tors)  # Hom(H_3) = 0 since H_3 torsion
    H4coh_tors = [3] if H3[1] else []  # Ext(H_3); Hom(H_4)=0 (H_4 torsion)
    H4coh = (0, H4coh_tors)
    ok = (orderH4 == 3) and (H5 == (0, []))
    rows.append((A0, B0, C0, orderH4, H5 == (0, []), ok))
for (A0, B0, C0, o4, h5z, ok) in rows:
    print(f"    A={'iso ' if A0 else '0   '} B'={'iso ' if B0 else '0   '} "
          f"C'={'iso ' if C0 else '0   '}  |H_4|={o4}  H_5=0:{str(h5z):5s}  "
          f"{'CONSISTENT' if ok else 'REJECTED'}")
surv = [r for r in rows if r[5]]
print(f"""
  SURVIVING homology configurations: {len(surv)} of 8 (raw labels).
  ==> TWO STRUCTURAL RESULTS (machine-derived, new vs Wave 8b):
    (R1) ANTI-CORRELATION:  B' = iso  <=>  C'(effective) = 0;
                             B' = 0    <=>  C' = iso.
        [from |H_4| = 3 (PD1) + H_5 = 0 (PD2); C' is the homology-side
         d5: E5_(5,0) -> E5_(0,4), invisible on the cohomology page.]
    (R2) The cohomology side (Wave 8b theorems + UCT glue) forces
         |H^4| = |Ext(H_3)|, i.e. the BIT is tied to A:
             bit = 0  <=>  A = 0  (H_2 = Z/3, H_3 = Z/3, H^4 = Z/3)
             bit = iso <=>  A = iso (H_2 = H_3 = 0,    H^4 = 0)
  But NOTHING in the E2 algebra + PD + UCT decides A (= the bit) itself.
  The bit is exactly the map A = d3_(3,0)->(0,2) (homology side) =
  d3^(1,2)->(4,0) (cohomology side, Wave 8b).  Both remain OPEN.""")
assert len(surv) == 6  # raw labels; C' is vacuous when B'=iso (acts on ker B'=0)

# careful recount: consistent ones:
# A=iso: H2=H3=0: UCT: H^3 = 0, H^4 = 0 => cohomology bit = iso-world.
#        PD1 |H_4| = 3: B'=iso => o4 = 1*3 = 3 OK; B'=0 => o4 = 3*(C'-dep)
#        B'=0, C'=iso: o4 = 3*1 = 3 OK, H5 = 0 OK  => ALSO consistent!!
# Hmm: A=iso, B'=0, C'=iso: check H5: ker B' = Z/3, C'=iso => H5 = 0 OK.
#      o4 = 3*1 = 3 OK.  So A=iso has (B'=iso,C'=any) and (B'=0,C'=iso).
# A=0: H2=H3=Z/3: UCT H^3 = Z/3, H^4 = Z/3: bit = 0-world.
#      B'=iso: o4 = 1*3 = 3 OK H5=0 OK => consistent.
#      B'=0,C'=iso: o4 = 3, H5 = 0 OK => consistent.  B'=0,C'=0: H5=Z/3 REJ.
# So survivors: A=iso: (iso,0),(iso,1)... wait (B'=iso, C' = anything since
# C' acts on ker B' = 0): C' label irrelevant: 2 labeled rows; (B'=0,C'=iso):
# 1 row; A=0: (B'=iso, C'-any): 2 rows; (B'=0, C'=iso): 1 row.  Total 6 rows
# but C'-vacuous rows are duplicates.  Distinct configurations: 4:
#   (A, B', C'-effective) = (iso, iso, 0), (iso, 0, iso), (0, iso, 0), (0, 0, iso)
# The anti-correlation R1 holds in all: B' iso <=> C'-effective = 0.
# Recount with effective C':
surv2 = [(A0, B0, 0 if B0 else C0) for (A0, B0, C0, *_ , ok) in rows if ok]
assert sorted(set(surv2)) == [(0, 0, 1), (0, 1, 0), (1, 0, 1), (1, 1, 0)], sorted(set(surv2))
print("  [ok] effective configurations: A x (B' XOR C') -- anti-correlation (R1) exact.")
print("  [ok] R2: the UCT glue (H^4 = Ext(H_3)) ties the cohomological BIT to A;")

# =====================================================================
# Section 4: QUQUART twisted homology side
# =====================================================================
hdr("SECTION D: QUQUART (d=4) -- twisted homology page and the H_9 mirror")
# C4 action on H^{2k}(Fl_4) from the coinvariant ring; twisted by the
# orientation character w (g |-> -1) for the Z~-valued SS.
def coinvariant_module(d, k):
    """Degree-k part of Z[x_1..x_d]/(e_1..e_d) with the cyclic variable
    shift matrix, in the descent basis {a_i <= d-1-i}.  Exact integer math."""
    from itertools import combinations
    all_mons = []
    def rec(i, rem, acc):
        if i == d:
            if rem == 0:
                all_mons.append(tuple(acc))
            return
        for v in range(rem + 1):
            rec(i + 1, rem - v, acc + [v])
    rec(0, k, [])
    idx = {m: i for i, m in enumerate(all_mons)}
    N = len(all_mons)
    # relations: e_j * (monomials of degree k-j), each as ONE summed vector
    rel_vecs = []
    for j in range(1, min(d, k) + 1):
        base = []
        def rec2(i, rem, acc):
            if i == d:
                if rem == 0:
                    base.append(tuple(acc))
                return
            for v in range(rem + 1):
                rec2(i + 1, rem - v, acc + [v])
        rec2(0, k - j, [])
        for bm in base:
            vec = [0] * N
            for S in combinations(range(d), j):
                ex = list(bm)
                for i in S:
                    ex[i] += 1
                ex = tuple(ex)
                if ex in idx:
                    vec[idx[ex]] += 1
            if any(vec):
                rel_vecs.append(vec)
    L = reduce_basis(rel_vecs) if rel_vecs else []
    std = [m for m in all_mons if all(m[i] <= d - 1 - i for i in range(d))]
    # sanity: descent count = Mahonian rank
    rank = len(std)
    # the relation lattice must have corank = rank
    # (rank of L as a subgroup of Z^N):
    rl = lattice_rank(L) if L else 0
    assert N - rl == rank, f"descent basis mismatch: N={N}, rankL={rl}, std={rank}"

    def solve_cols(cols, vec):
        n = len(vec); r = len(cols)
        M = [[Fraction(cols[j][i]) for j in range(r)] + [Fraction(vec[i])]
             for i in range(n)]
        piv = []
        row_i = 0
        for col in range(r):
            p = None
            for i in range(row_i, n):
                if M[i][col] != 0:
                    p = i; break
            if p is None:
                continue
            M[row_i], M[p] = M[p], M[row_i]
            pv = M[row_i][col]
            M[row_i] = [x / pv for x in M[row_i]]
            for i in range(n):
                if i != row_i and M[i][col] != 0:
                    f = M[i][col]
                    M[i] = [a - f * b for a, b in zip(M[i], M[row_i])]
            piv.append(col); row_i += 1
        for i in range(row_i, n):
            if M[i][r] != 0 and all(M[i][t] == 0 for t in range(r)):
                raise AssertionError("no solution in solve_cols")
        x = [Fraction(0)] * r
        for ridx, col in enumerate(piv):
            x[col] = M[ridx][r]
        for i in range(n):
            s = sum(x[j] * cols[j][i] for j in range(r))
            if s != Fraction(vec[i]):
                raise AssertionError("bad solve in solve_cols")
        assert all(v.denominator == 1 for v in x), "non-integral reduction"
        return [int(v) for v in x]

    def reduce_to_std(vec):
        cols = []
        for m in std:
            v = [0] * N
            v[idx[m]] = 1
            cols.append(v)
        cols = cols + [list(l) for l in L]
        coeffs = solve_cols(cols, vec)
        return coeffs[:len(std)]

    def shift_mon(m):
        return tuple([m[-1]] + list(m[:-1]))  # x_i -> x_{i+1}: exponents rotate

    A = [[0] * rank for _ in range(rank)]
    for i, m in enumerate(std):
        sm = shift_mon(m)
        v = [0] * N
        v[idx[sm]] = 1
        coeffs = reduce_to_std(v)
        for j, c in enumerate(coeffs):
            A[j][i] = c
    P = A
    for _ in range(d - 1):
        P = mat_mul(P, A)
    assert P == [[1 if i == j else 0 for j in range(rank)] for i in range(rank)], \
        f"shift^{d} != I on degree {k}"
    return A, std

print("  building C_4-modules from the coinvariant ring (exact, SNF-backed)...")
A1, _ = coinvariant_module(4, 1)
A2, _ = coinvariant_module(4, 2)
print(f"  H^2(Fl_4)-module: rank {len(A1)}  (want 3)")
assert len(A1) == 3
# check char poly t^3+t^2+t+1 via trace/eigen counts
tr = sum(A1[i][i] for i in range(3))
print(f"    trace(sigma) = {tr} (eigenvalue-1 count = 0 expected) ; "
      f"trace(sigma^2) = {sum(mat_mul(A1, A1)[i][i] for i in range(3))}")
# twisted modules: g |-> w(g) * A  = -A
Mtw = [[-x for x in row] for row in A1]
hTw = cyc_hom(Mtw, 4, 12)
cTw = cyc_coh(Mtw, 4, 12)
print("  H_p(C4; H_2(Fl_4) x Z~): " + " ".join(f"{gstr(*hTw[p]):>6}" for p in range(13)))
print("  H^p(C4; H_2(Fl_4) x Z~): " + " ".join(f"{gstr(*cTw[p]):>6}" for p in range(13)))
# Wave 8b values: H^0 = Z, H^1 = 0, H^2 = Z/2
assert cTw[0] == (1, []) and cTw[1] == (0, []) and cTw[2] == (0, [2])
print("    [ok] matches Wave 8b's twisted page (H^0 = Z, H^1 = 0, H^2 = Z/2)")
Zsign = [[-1]]
hZt = cyc_hom(Zsign, 4, 12)
cZt = cyc_coh(Zsign, 4, 12)
print("  H_p(C4; Z~):  " + " ".join(f"{gstr(*hZt[p]):>4}" for p in range(13)))
print("  H^p(C4; Z~):  " + " ".join(f"{gstr(*cZt[p]):>4}" for p in range(13)))
assert cZt[3] == (0, [2])
print("""
  QUQUART BIT (Wave 8b): H^3(B_4;Z~) = coker( d3: E3^{0,2} = Z -> E3^{3,0} = Z/2 )
     = Z/2 if the twisted d3 is ZERO,  = 0 if surjective.
  TWISTED PD: H^k(B_4;Z~) ~ H_{12-k}(B_4;Z~)  ==> the bit reappears as
     |H_9(B_4;Z~)| = |H^3(B_4;Z~)| = 2 or 1.
  Homology entries with p+q = 9 (q even, p odd):
     (9,0) = H_9(C4; Z~); (7,2) = H_7(C4; H_2 x Z~); (5,4) = H_5(C4; H_4 x Z~);
     (3,6); (1,8);  [(0,9) = H_0(C4; H_9(Fl_4)) = 0 (odd fiber cohomology)]
  Low-degree homology differentials touching total 9:
     a4 = d3: (12,0) -> (9,0);  b4 = d3: (10,2) -> (7,2); ...
  Incoming to the total-9 entries from total >= 12 (the staircase), plus the
  'bit-mirror' map  c4 = d3: (3,0) -> (0,2)  homologous-dual side of the
  cohomological d3: E3^{0,2} -> E3^{3,0}.""")
e90 = hZt[9]; e72 = hTw[7]
print(f"  (9,0) = {gstr(*e90)} ; (7,2) = {gstr(*e72)} ; (5,4) = H_5(C4;H_4 x Z~) (computed below)")
# H_4(Fl_4) module = the degree-2 coinvariant module (rank 5), twisted:
Mtw2 = [[-x for x in row] for row in A2]
hTw2 = cyc_hom(Mtw2, 4, 6)
print(f"  (5,4) = {gstr(*hTw2[5])}")
# H_6(Fl_4): rank 6 module; build
A3, _ = coinvariant_module(4, 3)
Mtw3 = [[-x for x in row] for row in A3]
hTw3 = cyc_hom(Mtw3, 4, 6)
print(f"  (3,6) = {gstr(*hTw3[3])}")
# H^8(Fl_4) = degree-4 coinvariant module (rank 5) -- NOT the same module as
# degree 2 (trace(sigma) differs: 1 vs 0); build it explicitly.
A4, _ = coinvariant_module(4, 4)
Mtw4 = [[-x for x in row] for row in A4]
hTw4 = cyc_hom(Mtw4, 4, 6)
print(f"  (1,8) = {gstr(*hTw4[1])}")

print("""
  RESULT: the total-9 homology entries are ALL FINITE TORSION, so
      |H_9(B_4;Z~)| = prod |E_inf pieces|  IS a valid product constraint,
  and twisted PD pins its value to the QUQUART BIT:
      |H_9| = |H^3(B_4;Z~)| = 2 (bit = 0)  or  1 (bit surjective).
  Raw pieces: |(7,2)| * |(5,4)| * |(3,6)| * |(1,8)| = 2*4*2*1 = 16 must be
  cut down to 2 or 1 by the incoming homology differentials
      d3: (10,2)->(7,2);  d3: (8,4)->(5,4);  d3: (6,6)->(3,6);  d3: (4,8)->(1,8)
  (sources again finite, sitting at total >= 12, themselves killed by the
  higher staircase).  This is exactly the qutrit's B'-XOR-C' structure in a
  richer lattice (Z/4 pieces allow 2-to-1 maps, so the surviving pattern has
  more room, but the CONSTRAINT is the same shape: a system of anti-
  correlations among the homology-side d3's, forced by PD + finiteness).
  It does NOT decide the bit: the ququart bit remains
      d3: E3^{0,2} = Z (anti-invariant class (1,-1,1,-1)) -> E3^{3,0} = Z/2.""")

# =====================================================================
# Section 5: negative result -- the k_2 formula refuted (recorded)
# =====================================================================
hdr("SECTION E: NEGATIVE RESULT (recorded to prevent future detours)")
print("""
  Candidate formula REFUTED:  'CLSS d3^{1,2} = <alpha u k_2>' where k_2 is
  the 2-Postnikov k-invariant of the action-fibration X -> X//G -> BG.

  Test case: X = BS^1 = K(Z,2) with C_2 acting by complex conjugation.
    Split extension  1 -> S^1 -> O(2) -> C_2 -> 1:
       E = B(O(2))  has a section (the C_2-split)  =>  k_2 = 0.
    Non-split extension (j^2 = -1 in S^1, the binary-dihedral group H'):
       E = B(H')  has no 2-torsion-free lift of the generator => k_2 != 0
       (k_2 = Bockstein of the nontrivial extension class in
        H^2(C_2; S^1_inv) = Z/2  ->  H^3(C_2; Z_inv) = Z/2).
  In BOTH cases the CLSS d3: E3^{1,2} = H^1(C_2; Z_sign) = Z/2 ->
  E3^{4,0} = H^4(C_2;Z) = Z/2 is ZERO, forced by UCT:
    H_2(E) = coinvariants of H_2(fiber) = Z/2  (forced by E2_{0,2}),
    hence H^3(E) = Ext(H_2) = Z/2 must survive from E3^{1,2}, so d3 = 0.
  k_2 differs between the two cases; d3 does not.  Hence d3^{1,2} is NOT
  the cup-pairing with the 2-stage k-invariant.  (The (0,2)-transgression
  is k_2-flavored only when H^2(fiber)^G != 0, which fails in all our cases.)

  Consequence: no shortcut through the equivariant Postnikov 2-type; the
  honest route remains the C_d-equivariant chain model of Fl_d
  (c-invariant CW structure / equivariant Morse complex), as planned.""")

hdr("VERDICT")
print("""
  QUTRIT bit   (d3: E3^{1,2} -> E3^{4,0}, equivalently A = d3_{(3,0)->(0,2)}):
      OPEN.  New machine results: anti-correlation (R1) B' XOR C'; A <-> bit.
  QUQUART bit (twisted d3: E3^{0,2} = Z -> E3^{3,0} = Z/2):
      OPEN.  Homology mirror located at total degree 9; product structure
      verified finite (constraint structure analogous to the qutrit's).
  Numerical evidence (Wave 8a, verify_wave8.py) continues to favor
      delta_2(qutrit) = 4/3  and  delta_1(ququart) = 3/2
  (both transgressions vanishing), but this remains unproven.
  The decisive step -- the honest equivariant chain model -- is still
  unbuilt; everything short of it is now machine-mapped.""")
print("\nWAVE 8c done.  No claim made on either bit; manuscripts untouched.")
