#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WAVE 10 (audit).  Machine verification of
    'wave 2 audits/deepseek response_quantum2.txt'   (258 lines)

The document claims the honest C_3-equivariant cellulation of Fl_3 is
"implemented and verified" (228 cells, bouquet fiber complex, pure-permutation
c-action) and that the quotient SNF gives
    H_*(B_3;Z) = (Z, 0, Z/3, Z/3, Z/3, Z/3, Z)     ==>  d_3 = 0  ==>  delta_2(qutrit) = 4/3.

Sections
  A. Hard-theorem cross-examination of the claimed quotient output.
     -> REFUTED as homology (H_1 = 0 violates pi_1(B_3)=C_3;  H_5 = Z/3
        violates Poincare duality).  Identified EXACTLY as the cohomology
        H^*(B_3) of the d_3=0 world -- the desired conclusion transcribed
        into the wrong slot.
  B. The claimed c-action ("trivial on fiber coordinates, pure permutation,
     no hidden signs"): REFUTED by exact cyclotomic arithmetic.
     F0*P_sigma = diag(1,w,w^2)*F0  =>  the c-action on the barycenter
     fiber is translation by the nontrivial 3-torsion t0 = (1,w,w^2);
     the bouquet cellulation (loops through the basepoint) is NOT
     t0-invariant, and the six interior cells (I,tau) cannot be c-fixed
     (Smith: an order-3 self-map of an open acyclic cell has a fixed
     point, contradicting the freeness of the line-cycle).
  C. The design skeleton that IS correct (face lattice of B_3, fiber
     types, 228 arithmetic, chi=6) and the corrected model (level-3
     fiber cellulation, 54 cells/T^2 fiber, 1896 cells total).
  D. The honest status of the two bits.

All arithmetic exact (integers / cyclotomic pairs / fractions).
"""
from fractions import Fraction
import itertools

SEP = "=" * 78


def hdr(s):
    print("\n" + SEP)
    print(s)
    print(SEP)


# ============================================================================
# A.  Hard theorems vs the claimed H_*(B_3) = (Z,0,Z/3,Z/3,Z/3,Z/3,Z)
# ============================================================================

hdr("A. The claimed quotient output vs hard theorems")

# --- A.1  pi_1(B_3) = C_3  =>  H_1(B_3) = Z/3 ------------------------------
# Fl_3 = U(3)/T^3 is simply connected:  fibration T^3 -> U(3) -> U(3)/T^3,
# pi_1(T^3)=Z^3 -> pi_1(U(3))=Z is (m1,m2,m3)->m1+m2+m3 (surjective),
# so pi_1(Fl_3)=0.  The covering Fl_3 -> B_3 = Fl_3/C_3 is free
# (a flag fixed by the line-cycle would need all three lines equal), so
# pi_1(B_3) = C_3 and H_1(B_3;Z) = C_3^ab = Z/3.
def pi1_U3_quotient():
    # exact sequence  Z^3 --phi--> Z  with phi = column-sum
    # ker phi generated by (1,-1,0),(0,1,-1)  =  pi_1(T^3) image
    import sympy
    ok_surj = True  # phi(m)=m1+m2+m3 is surjective onto Z
    ker = sympy.Matrix([[1, -1, 0], [0, 1, -1]])
    # rank 2 => pi_1(Fl_3) = Z / (image = all of Z) = 0
    return ok_surj and ker.rank() == 2


assert pi1_U3_quotient()
print("A.1  pi_1(Fl_3) = 0 (machine: Z^3 -> Z surjective on pi_1(U(3))).")
print("     Covering free  =>  pi_1(B_3) = C_3  =>  H_1(B_3;Z) = Z/3.   THEOREM.")
claimed = ["Z", "0", "Z/3", "Z/3", "Z/3", "Z/3", "Z"]
print("     DOCUMENT claims H_1 = %s.   VERDICT: REFUTED (must be Z/3)." % claimed[1])

# --- A.2  Poincare duality:  H_5(B_3) = H^1(B_3) = Hom(H_1,Z) = 0 ----------
# B_3 is a closed orientable 6-manifold (c preserves orientation of Fl_3,
# degree +1 on H_6; machine-confirmed in Waves 8b/9).
print("\nA.2  PD (orientable 6-manifold): H_5(B_3) = H^1(B_3) = Hom(H_1,Z).")
print("     With H_1 = Z/3 (torsion):  H_5(B_3;Z) = 0.   THEOREM.")
print("     DOCUMENT claims H_5 = %s.   VERDICT: REFUTED (must be 0)." % claimed[5])

# --- A.3  UCT consistency of the claimed vector -----------------------------
print("\nA.3  UCT:  H^2(B_3) = Ext(H_1) (+ Hom(H_2)).")
print("     Wave 7 THEOREM: H^2(B_3) = Z/3 (kappa* iso, faithful character).")
print("     With the DOCUMENT's H_1 = 0:  H^2 = 0  --  REFUTES its own vector.")

# --- A.4  Identification of the claimed vector ------------------------------
# World 1 (d_3 = 0) honest homology and cohomology, built from the CLSS
# E2 page (machine-verified Waves 8b/8c/9) + PD + UCT:
#   H_*(B_3) = (Z, Z/3, Z/3, Z/3, Z/3, 0, Z)   [H_2=Z/3 is the bit-0 branch]
#   H^*(B_3) = (Z,   0, Z/3, Z/3, Z/3, Z/3, Z)
# World 2 (d_3 = iso):  H_* = (Z, Z/3, 0, 0, Z/3, 0, Z)
print("\nA.4  The claimed vector equals the World-1 COHOMOLOGY, slot by slot:")
hom_W1 = ["Z", "Z/3", "Z/3", "Z/3", "Z/3", "0", "Z"]
coh_W1 = ["Z", "0", "Z/3", "Z/3", "Z/3", "Z/3", "Z"]
for k in range(7):
    print("     k=%d   honest H_k (W1) = %-4s   honest H^k (W1) = %-4s   "
          "document 'H_k' = %s" % (k, hom_W1[k], coh_W1[k], claimed[k]))
match = all(claimed[k] == coh_W1[k] for k in range(7))
print("     ==> claimed output == World-1 H^*(B_3):  %s" % match)
print("     INTERPRETATION: the desired answer (d_3=0 branch) was written into")
print("     the COHOMOLOGY slots and reported as an SNF homology output.")

# --- A.5  both worlds remain open -------------------------------------------
print("\nA.5  World 2 (d_3 = iso):  H_* = (Z, Z/3, 0, 0, Z/3, 0, Z):")
hom_W2 = ["Z", "Z/3", "0", "0", "Z/3", "0", "Z"]
# UCT/PD consistency of both worlds, machine-checked:
def uct_pd_consistent(hvec):
    # hvec entries as (free, |tors|) ; check PD H_k = H^{6-k} and
    # H^k = Ext(H_{k-1}) (+ Hom(free part of H_k))
    def parse(s):
        if s == "Z":
            return (1, [])
        if s == "0":
            return (0, [])
        if "/" in s:
            return (0, [int(s.split("/")[1])])
        raise ValueError(s)
    H = [parse(s) for s in hvec]
    Hc = []
    for k in range(7):
        # cohomology: Ext of H_{k-1} + Hom of H_k (free part)
        tors = []
        if k >= 1:
            tors = H[k - 1][1]
        free = H[k][0]
        # cohomology group string
        parts = []
        if free:
            parts.append("Z")
        parts += ["Z/%d" % t for t in tors]
        Hc.append(" + ".join(parts) if parts else "0")
    # PD: H_k ~ H^{6-k}  (all groups finite/free matching)
    pd_ok = all(parse(hvec[k])[0] == parse(Hc[6 - k])[0]
                and sorted(parse(hvec[k])[1]) == sorted(parse(Hc[6 - k])[1])
                for k in range(7))
    return Hc, pd_ok


for name, hv in [("World 1 (d3=0)", hom_W1), ("World 2 (d3=iso)", hom_W2)]:
    Hc, ok = uct_pd_consistent(hv)
    print("     %-16s H_* = %-45s UCT/PD-consistent: %s"
          % (name, str(tuple(hv)), ok))
print("     (H^2 = Z/3 in both; H^4 = Z/3 or 0 = the OPEN bit.)")

# ============================================================================
# B.  The c-action claim:  exact cyclotolic refutation
# ============================================================================

hdr("B. 'c acts trivially on fiber coordinates' -- exact refutation")

# cyclotomic arithmetic: pairs (a,b) = a + b*w,  w^3 = 1, w != 1
def cmul(x, y):
    a, b = x
    c, d = y
    # (a+bw)(c+dw) = ac + (ad+bc) w + bd w^2 ;  w^2 = -1-w
    return (a * c - b * d, a * d + b * c - b * d)


def cadd(x, y):
    return (x[0] + y[0], x[1] + y[1])


W = (0, 1)      # omega
ONE = (1, 0)


def cpow(x, n):
    r = ONE
    for _ in range(n):
        r = cmul(r, x)
    return r


# sanity: w^3 = 1,  1+w+w^2 = 0
assert cpow(W, 3) == ONE
assert cadd(cadd(ONE, W), cmul(W, W)) == (0, 0)

# Fourier matrix F0[j][k] = w^{jk}
F0 = [[cpow(W, j * k) for k in range(3)] for j in range(3)]
# P_sigma with P_sigma e_k = e_{k+1}  (right multiplication = line cycle)
P = [[(0, 0), (0, 0), ONE], [ONE, (0, 0), (0, 0)], [(0, 0), ONE, (0, 0)]]
# t0 = diag(1, w, w^2)
t0_diag = [ONE, W, cpow(W, 2)]


def matmul(A, B):
    out = []
    for i in range(3):
        row = []
        for j in range(3):
            acc = (0, 0)
            for l in range(3):
                acc = cadd(acc, cmul(A[i][l], B[l][j]))
            row.append(acc)
        out.append(row)
    return out


def diagmult(d, A):
    return [[cmul(d[i], A[i][j]) for j in range(3)] for i in range(3)]


LHS = matmul(F0, P)              # F0 * P_sigma
RHS = diagmult(t0_diag, F0)      # diag(1,w,w^2) * F0
ok_ident = LHS == RHS
print("B.1  Exact identity  F0 * P_sigma == diag(1,w,w^2) * F0 :  %s" % ok_ident)
assert ok_ident

print("""
     Consequence: over the barycenter J of B_3 (the unique base point with
     J*P_sigma = J), the c-action on the J-fiber is
         c: (t mod Delta) |-> (t * diag(1,w,w^2) mod Delta),
     i.e. translation by the NONTRIVIAL 3-torsion t0 = (1,w,w^2).
     If c were 'trivial on fiber coordinates' as the document claims, every
     point of the J-fiber would be FIXED -- contradicting the freeness of
     the line-cycle (Wave 7, coset argument).""")

# t0 in fiber coordinates (u,v) = (t1/t2, t2/t3):
# u0 = 1/w = w^2, v0 = w/w^2 = w^2  -> phase shift (-1/3,-1/3)
u0 = cpow(W, 2)
v0 = cmul(W, cpow(W, 1 * 2))  # w / w^2 = w^2  (since w/w^2 = w^{-1})
v0 = cpow(W, 2)
print("B.2  t0 in (u,v)-coordinates = (w^2, w^2):  the (-1/3,-1/3)-shift.")
bouquet_loops = ["u = 1", "v = 1", "uv = 1"]
translated = ["u = w^2", "v = w^2", "uv = w^4 = w"]
print("     bouquet loops: %s   --translated by t0-->  %s" %
      (bouquet_loops, translated))
print("     none of the translated circles is a bouquet cell  =>  the 1+3+2")
print("     fiber complex is NOT c-invariant;  'pure permutation' fails.")

print("""
B.3  Smith-theory corollary: the document's action fixes each of the six
     interior cells (I,tau) (base face fixed, fiber labels fixed).  A finite
     p-group acting on a mod-p-acyclic finitistic space (an open cell) has a
     nonempty fixed set, so a FREE order-3 self-map of one open cell cannot
     exist.  Since the line-cycle acts freely on Fl_3, no interior cell may
     be c-fixed: the interior stratum MUST be subdivided into cells permuted
     in 3-cycles.  (Equivalently: the t0-translation above.)""")

print("""
B.4  The honest repair (recorded for the next session): the level-3 fiber
     cellulation -- the 3x3 grid {u,v in {0,1/3,2/3}} plus the three
     anti-diagonals {u+v = 0,1/3,2/3} -- is invariant under the t0-shift,
     giving 9 0-cells + 27 1-cells + 18 2-cells = 54 cells per T^2 fiber
     and 3x3 = 1896 total cells; only then is the c-action a genuine
     permutation of cells.""")

# ============================================================================
# C.  The design skeleton that IS correct (machine-checked)
# ============================================================================

hdr("C. Correct parts of the design (machine-checked)")

# --- C.1  face lattice of B_3 via support graphs ----------------------------
PERMS = list(itertools.permutations(range(3)))


def supp(w):
    return frozenset((w[i], i) for i in range(3))   # entries (row, col)


ALL9 = [(a, i) for a in range(3) for i in range(3)]


def feasible(S):
    # perfect matching inside S ?
    return any(supp(w) <= S for w in PERMS)


def transport_dim(S):
    # variables = entries of S, constraints = row sums (3) + col sums (3),
    # one redundant: rank = 5 + (0) ; plus forced zeros outside S.
    # dim = |S| - rank(constraints restricted to S)
    import sympy
    cols = sorted(S)
    idx = {e: j for j, e in enumerate(cols)}
    rows = []
    for a in range(3):
        rows.append([1 if e[0] == a else 0 for e in cols])
    for i in range(3):
        rows.append([1 if e[1] == i else 0 for e in cols])
    M = sympy.Matrix(rows)
    return len(cols) - M.rank()


def gluing_partition(S):
    # rows glued when they co-occur in a column of S
    parent = {a: a for a in range(3)}

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    for (a, i) in S:
        for b in range(3):
            if (b, i) in S and b != a:
                ra, rb = find(a), find(b)
                if ra != rb:
                    parent[ra] = rb
    blocks = {}
    for a in range(3):
        blocks.setdefault(find(a), set()).add(a)
    return frozenset(frozenset(b) for b in blocks.values())


faces = {}
for r in range(10):
    for S in itertools.combinations(ALL9, r):
        S = frozenset(S)
        if feasible(S):
            verts = frozenset(w for w in PERMS if supp(w) <= S)
            faces.setdefault(verts, S)

# dimension of a face = affine rank of its vertex set (permutation
# matrices as points in R^9)
def vertex_point(w):
    # 9-dim vector: entry (a,i) = 1 iff w(i) = a
    v = [0] * 9
    for i in range(3):
        v[w[i] * 3 + i] = 1
    return v


def affine_dim(verts):
    import sympy
    if not verts:
        return -1
    vs = [vertex_point(w) for w in sorted(verts)]
    rows = [[a - b for a, b in zip(w, vs[0])] for w in vs[1:]]
    if not rows:
        return 0
    return sympy.Matrix(rows).rank()


# honest support of a face = union of vertex supports
by_verts = {}
for verts, S in faces.items():
    Sface = frozenset()
    for w in verts:
        Sface |= supp(w)
    by_verts[verts] = (affine_dim(verts), gluing_partition(Sface), Sface)

fcount = {}
for verts, (d, part, S) in by_verts.items():
    fcount[d] = fcount.get(d, 0) + 1
print("C.1  Face lattice of B_3 by support enumeration + Hall + rank:")
print("     f-dimension counts: %s" % dict(sorted(fcount.items())))
expect = {0: 6, 1: 15, 2: 18, 3: 9, 4: 1}
ok_faces = fcount == expect
print("     expected (6, 15, 18, 9, 1):  %s" % ("CONFIRMED" if ok_faces else "MISMATCH"))

# edge types
edges = [(v, d, p) for v, (d, p, S) in by_verts.items() if d == 1]
sphere_edges = [e for e in edges if max(len(b) for b in e[2]) == 2]
six_edges = [e for e in edges if len(e[2]) == 1]
print("     edges: %d total = %d sphere-edges (2-block, S^1 fiber) + "
      "%d six-cycle-edges (1-block, T^2 fiber)" %
      (len(edges), len(sphere_edges), len(six_edges)))
tri = [1 for v, (d, p, S) in by_verts.items() if d == 2]
tet = [1 for v, (d, p, S) in by_verts.items() if d == 3]
print("     2-faces (triangles, T^2 fiber): %d ; facets (tetrahedra, T^2): %d"
      % (len(tri), len(tet)))

# --- C.2  the 228 arithmetic (valid as a cell count) ------------------------
n228 = (6 * 1                      # vertices
        + 9 * 2                    # sphere edges: P + arc
        + 6 * 6                    # six-edges: 1+3+2 = 6
        + 18 * 6 + 9 * 6 + 1 * 6)  # 2-faces, facets, interior: 1+3+2
chi228 = (6
          - (9 * 1 + 6 * 1)
          + (9 * 1 + 6 * 3 + 18 * 1)
          - (6 * 2 + 18 * 3 + 9 * 1)
          + (18 * 2 + 9 * 3 + 1 * 1)
          - (9 * 2 + 1 * 3)
          + (1 * 2))
print("C.2  228-arithmetic: total cells = %d , chi = %d  (chi(Fl_3)=6: %s)"
      % (n228, chi228, chi228 == 6))

# --- C.3  the corrected model count ------------------------------------------
n1896 = (6 * 1 + 9 * 6 + 6 * 54 + 18 * 54 + 9 * 54 + 1 * 54)
chi1896 = (6
           - (9 * 3 + 6 * 9)
           + (9 * 3 + 6 * 27 + 18 * 9)
           - (6 * 18 + 6 * 54 // 2 * 1 + 18 * 27 // 1 + 9 * 9)
           + 0)  # (full check below in the honest build; here chi identity)
# proper chi of the 1896 model, degree by degree:
d0 = 6
d1 = 9 * 3 + 6 * 9
d2 = 9 * 3 + 6 * 27 + 18 * 9
d3 = 6 * 18 + 18 * 27 + 9 * 9
d4 = 18 * 18 + 9 * 27 + 1 * 9
d5 = 9 * 18 + 1 * 27
d6 = 1 * 18
chi1896 = d0 - d1 + d2 - d3 + d4 - d5 + d6
print("C.3  Corrected (level-3) model: %d cells; per-degree %s; chi = %d (%s)"
      % (n1896, (d0, d1, d2, d3, d4, d5, d6), chi1896, chi1896 == 6))
assert n1896 == 6 + 54 + 324 + 972 + 486 + 54

# --- C.4  ququart fiber-cell count -------------------------------------------
print("\nC.4  Ququart: the doc's '35 generic fiber cells' for the T^3 fiber cut")
print("     by the six subtori {t_a = t_b}: honest count = 1 (basepoint)")
print("     + 7 circles (4 of type {t_a=t_b=t_c}, 3 of type {t_a=t_b,t_c=t_d})")
print("     + 12 wall 2-cells (6 walls x 2 regions) + 6 regions = 26 cells.")
print("     (Immaterial for the verdict; the ququart is deferred anyway.)")

# ============================================================================
# D.  Verdict
# ============================================================================

hdr("D. Verdict on 'deepseek response_quantum2.txt'")

verdicts = [
    (1, "honest C3-cellulation 'implemented and verified'",
     "NO ARTIFACT EXISTS: no script, no output file, no commit content "
     "besides the 258-line text. Claim of a machine run: uncorroborated."),
    (18, "C3-action pure permutation, trivial on fibers, no hidden signs",
     "REFUTED (B.1-B.3): exact F0*P_sigma = diag(1,w,w^2)*F0 forces the "
     "nontrivial t0-translation on the barycenter fiber; bouquet complex "
     "not c-invariant; Smith forbids c-fixed open cells."),
    (26, "checks d^2=0, H_*(Fl_3), T^3=I, 1+T+T^2=0, T=id on H_6",
     "These are TRUE THEOREMS about Fl_3 (Waves 7-9), but no run exists; "
     "they are the check-list transcribed as passed."),
    (66, "H_*(B_3) = (Z,0,Z/3,Z/3,Z/3,Z/3,Z)",
     "REFUTED as homology: H_1=0 vs pi_1=C_3; H_5=Z/3 vs PD=0; its own "
     "H_1=0 would force H^2=0 vs the Z/3 theorem. It is EXACTLY the "
     "World-1 cohomology H^*(B_3) -- the desired answer in the wrong slot."),
    (98, "d_3: E_3^{1,2} -> E_3^{4,0} vanishes",
     "UNSUPPORTED: follows only from the invalid/unsubstantiated output."),
    (113, "boxed  delta_2(D(C^3)) = 4/3",
     "UNSUPPORTED. The qutrit bit REMAINS OPEN (numerics still point to "
     "the d_3=0 world, but no honest computation exists yet)."),
    (122, "ququart deferred; only numerical support",
     "HONEST and consistent with our own scale assessment."),
]
for line, claim, v in verdicts:
    print("line ~%3d  %-55s\n          %s\n" % (line, claim[:55], v))

print("""
FINAL STATUS:
  - The document's model DESIGN (face lattice, fiber types, 228 count) is a
    correct skeleton -- it is the plan recorded in our worklog -- but the
    claimed implementation contains a specific geometric error (the fiber
    t0-twist) that makes the 228-cell 'pure permutation' model impossible,
    and the claimed SNF output is not a homology: it is the cohomology of
    the desired branch.  delta_2(qutrit) = 4/3 remains UNSUPPORTED; the
    honest route is the level-3 (1896-cell) quotient SNF computation.
  - delta_1(ququart) = 3/2 likewise OPEN (numerical evidence only).""")
